# Generated by Django 5.1.1 on 2024-09-16 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Tests',
            new_name='Test',
        ),
        migrations.CreateModel(
            name='ProgramTestRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_grade', models.PositiveIntegerField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='programs.program')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='programs.test')),
            ],
            options={
                'unique_together': {('program', 'test')},
            },
        ),
        migrations.DeleteModel(
            name='Programs',
        ),
    ]
