# Generated by Django 5.1.1 on 2024-09-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_program_rename_tests_test_programtestrequirement_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programtestrequirement',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='programtestrequirement',
            name='test',
        ),
        migrations.AddField(
            model_name='programtestrequirement',
            name='test',
            field=models.ManyToManyField(related_name='programs', to='programs.test'),
        ),
    ]
