# Generated by Django 5.1.1 on 2024-09-16 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_alter_programtestrequirement_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='minimum_grade',
        ),
        migrations.AddField(
            model_name='program',
            name='tests',
            field=models.ManyToManyField(related_name='programs', through='programs.ProgramTestRequirement', to='programs.test'),
        ),
        migrations.AlterField(
            model_name='programtestrequirement',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_requirements', to='programs.program'),
        ),
        migrations.AlterUniqueTogether(
            name='programtestrequirement',
            unique_together={('program', 'test')},
        ),
        migrations.RemoveField(
            model_name='programtestrequirement',
            name='test',
        ),
        migrations.AddField(
            model_name='programtestrequirement',
            name='test',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='program_requirements', to='programs.test'),
            preserve_default=False,
        ),
    ]
