# Generated by Django 5.1.1 on 2024-09-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_institutes_program_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutes',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
