# Generated by Django 5.1.1 on 2024-09-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_institutes_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='details',
            field=models.TextField(max_length=550),
        ),
    ]
