# Generated by Django 5.1.1 on 2024-09-28 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='programs.program'),
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('details', models.TextField(max_length=600)),
                ('duration', models.PositiveIntegerField()),
                ('programs', models.ManyToManyField(related_name='program', to='programs.program')),
            ],
        ),
    ]
