# Generated by Django 5.1.1 on 2024-09-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('details', models.TextField(max_length=600)),
                ('duration', models.PositiveIntegerField()),
                ('credit', models.PositiveIntegerField(default=4)),
                ('grade', models.PositiveIntegerField(default=1)),
                ('programs', models.ManyToManyField(related_name='program', to='programs.program')),
            ],
        ),
    ]
