# Generated by Django 5.1.1 on 2024-09-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0010_alter_events_program_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='credit',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='courses',
            name='grade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
