# Generated by Django 5.1.1 on 2024-09-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0010_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='required_for', to='programs.courses'),
        ),
    ]
