# Generated by Django 5.1.1 on 2024-09-14 10:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChosenStudyField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_course', models.CharField(choices=[('math_analyses', 'Math Analyses')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudyFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2018), django.core.validators.MaxValueValidator(2024)])),
                ('image', models.ImageField(upload_to='')),
                ('study_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.chosenstudyfield')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
