# Generated by Django 5.1.1 on 2024-09-16 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_remove_test_minimum_grade_program_tests_and_more'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='study_field',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='chosen_major',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='programs.program'),
            preserve_default=False,
        ),
    ]
