# Generated by Django 5.1.1 on 2024-09-19 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_studentprofile_study_field_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChosenStudyField',
        ),
        migrations.DeleteModel(
            name='StudyFields',
        ),
    ]
