# Generated by Django 5.1.1 on 2024-09-21 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_studentprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='admission_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2018), django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
