# Generated by Django 5.1.1 on 2024-09-21 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_alter_program_details'),
        ('student', '0005_alter_studentprofile_admission_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='chosen_major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='programs.program'),
        ),
    ]
