# Generated by Django 5.1.1 on 2024-09-27 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
