# Generated by Django 5.1.1 on 2024-09-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0010_courses'),
        ('student', '0009_delete_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='chosen_courses',
            field=models.ManyToManyField(blank=True, null=True, to='programs.courses'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='events',
            field=models.ManyToManyField(blank=True, null=True, to='programs.events'),
        ),
    ]
