# Generated by Django 5.1.1 on 2024-09-29 11:31

import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_alter_studentprofile_admission_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='admission_year',
            field=models.IntegerField(blank=True, default=student.models.current_year, null=True, validators=[student.models.validate_admission_year]),
        ),
    ]
